# Generated by Django 3.2.8 on 2021-11-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Soc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('ic', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=200)),
                ('dateregister', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='ic_text',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='No. Kad Pengenalan'),
        ),
        migrations.AlterField(
            model_name='question',
            name='income',
            field=models.IntegerField(verbose_name='Income'),
        ),
    ]
