# Generated by Django 3.2.8 on 2021-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Soc', '0002_auto_20211119_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateregister',
            field=models.DateTimeField(verbose_name='%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ic_text',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
